source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

install! 'cocoapods',
#:deterministic_uuids=>false,
disable_input_output_paths: true,
warn_for_unused_master_specs_repo: false

use_frameworks!

target 'Down-Example' do
  pod 'Highlightr'
end
